In [1]:
import pygrib
import pandas as pd
import numpy as np

Read data

In [2]:
file = '/data/c02n03/archive/ds083.3/2015/gdas1.fnl0p25.2015081106.f00.grib2' #example filename
gr = pygrib.open(file)

In [3]:
df = pd.read_csv("../201508/AUTO_5MINS_NPP_MicroPhys_20150811_0455_Table.txt", sep='\s+',skiprows=0,header=0,na_values=[-99,-9999])

In [4]:
def find_nearest(array,value):
    idx = (np.abs(array-value)).argmin()
    return array[idx]

In [5]:
def potential_temperature(T,p):
    """Compute potential temperature for an air parcel.

    Input:  T is temperature in Kelvin
            p is pressure in mb or hPa
    Output: potential temperature in Kelvin.

    """
    ps=1000
    cp = 1004.     # specific heat at constant pressure for dry air (J / kg / K)
    Rd = 287.         # gas constant for dry air (J / kg / K)
    kappa = Rd/cp
    theta = T*(ps/p)**kappa
    return theta

In [6]:
#pblh=gr.select(name='Planetary boundary layer height')
#pblh
#pblh=pblh.values

In [7]:
pblh=gr.select(name='Planetary boundary layer height')[0]
pblhv=pblh.values
print(pblhv.shape)
print(np.amax(pblhv),np.amin(pblhv))

(721, 1440)
3966.0398 17.0


In [8]:
#get record number
ptems = gr[299] #Potential temperature
ptemsv=ptems.values
T1000= gr[208]
T1000v=T1000.values
Tsurf = gr[219]
Tsurfv=Tsurf.values
T500= gr[112]
T500v=T500.values
T850= gr[168]
T850v=T850.values
T700= gr[144]
T700v=T700.values
Gh1000= gr[216]
Gh1000v=Gh1000.values
Gh500= gr[111]
Gh500v=Gh500.values
Gh850= gr[167]
Gh850v=Gh850.values
Gh700= gr[143]
Gh700v=Gh700.values
ST0 = gr[220]
ST0v=ST0.values
Sli = gr.select(name='Surface lifted index')[0]
Sliv=Sli.values
B4li = gr.select(name='Best (4-layer) lifted index')[0]
B4liv=B4li.values
LSM = gr.select(name='Land-sea mask')[0]
LSMv=LSM.values
Tozone = gr.select(name='Total ozone')[0]
Tozonev=Tozone.values
Srh = gr.select(name='Storm relative helicity')[0]
Srhv=Srh.values
Cape = gr.select(name='Convective available potential energy')[0]
Capev=Cape.values
Pr = gr.select(name='Cloud water')[0]
Prv= Pr.values
Pw = gr.select(name='Precipitable water')[0]
Pwv=Pw.values
CIN0 = gr[243]
CIN0v =CIN0.values
CIN180 = gr[292]
CIN180v=CIN180.values
CIN255 = gr[305]
CIN255v=CIN255.values
Sh2 =gr [231]#Specific humidity 2m
Sh2v=Sh2.values
TD2 = gr.select(name='2 metre dewpoint temperature')[0]
TD2v=TD2.values
RH2 = gr.select(name='2 metre relative humidity')[0]
RH2v= RH2.values

In [9]:
ptem700v= potential_temperature(T700v, 700)
print(np.amax(ptem700v),np.amin(ptem700v))

331.86887 239.07404


In [10]:
lts= ptem700v-ptemsv

In [11]:
lts

array([[17.694    , 17.694    , 17.694    , ..., 17.694    , 17.694    ,
        17.694    ],
       [17.704742 , 17.704742 , 17.704742 , ..., 17.704742 , 17.704742 ,
        17.704742 ],
       [17.826202 , 17.826202 , 17.826202 , ..., 17.826202 , 17.826202 ,
        17.826202 ],
       ...,
       [-1.1672668, -1.1672668, -1.1672668, ..., -1.1672668, -1.1672668,
        -1.1672668],
       [-1.2350769, -1.1243286, -1.1243286, ..., -1.2350769, -1.2350769,
        -1.2350769],
       [-1.2350769, -1.2350769, -1.2350769, ..., -1.2350769, -1.2350769,
        -1.2350769]], dtype=float32)

In [12]:
print(lts.shape)
print(np.amax(lts),np.amin(lts))

(721, 1440)
37.706512 -12.907898


In [13]:
lat,lon=df["lat"],df["lon"]

In [14]:
lat,lon

(0       37.3944
 1       37.7066
 2       37.6469
 3       38.0790
 4       38.0190
 5       37.9589
 6       37.2766
 7       37.2183
 8       37.1595
 9       37.5887
 10      37.5302
 11      37.4709
 12      37.9006
 13      37.8419
 14      37.7827
 15      37.0978
 16      37.0378
 17      36.9768
 18      37.4093
 19      37.3490
 20      37.2878
 21      37.7207
 22      37.5986
 23      36.9146
 24      36.8511
 25      36.7857
 26      37.2254
 27      37.1616
 28      37.0959
 29      37.5360
          ...   
 3027    19.3975
 3028    23.6883
 3029    24.0741
 3030    23.9987
 3031    24.3838
 3032    24.3462
 3033    24.3093
 3034    23.6522
 3035    23.6172
 3036    23.5836
 3037    23.9630
 3038    23.9282
 3039    23.8618
 3040    23.8298
 3041    23.7997
 3042    23.3678
 3043    23.7685
 3044    23.9930
 3045    23.8880
 3046    23.1659
 3047    23.1193
 3048    23.4326
 3049    23.3892
 3050    23.7924
 3051    23.7459
 3052    23.7027
 3053    23.3353
 3054    23.27

In [15]:
lon_list,lat_list = ptems.latlons()[1][0],ptems.latlons()[0].T[0]

In [16]:
lon_list,lat_list

(array([0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5925e+02, 3.5950e+02,
        3.5975e+02]),
 array([ 90.  ,  89.75,  89.5 ,  89.25,  89.  ,  88.75,  88.5 ,  88.25,
         88.  ,  87.75,  87.5 ,  87.25,  87.  ,  86.75,  86.5 ,  86.25,
         86.  ,  85.75,  85.5 ,  85.25,  85.  ,  84.75,  84.5 ,  84.25,
         84.  ,  83.75,  83.5 ,  83.25,  83.  ,  82.75,  82.5 ,  82.25,
         82.  ,  81.75,  81.5 ,  81.25,  81.  ,  80.75,  80.5 ,  80.25,
         80.  ,  79.75,  79.5 ,  79.25,  79.  ,  78.75,  78.5 ,  78.25,
         78.  ,  77.75,  77.5 ,  77.25,  77.  ,  76.75,  76.5 ,  76.25,
         76.  ,  75.75,  75.5 ,  75.25,  75.  ,  74.75,  74.5 ,  74.25,
         74.  ,  73.75,  73.5 ,  73.25,  73.  ,  72.75,  72.5 ,  72.25,
         72.  ,  71.75,  71.5 ,  71.25,  71.  ,  70.75,  70.5 ,  70.25,
         70.  ,  69.75,  69.5 ,  69.25,  69.  ,  68.75,  68.5 ,  68.25,
         68.  ,  67.75,  67.5 ,  67.25,  67.  ,  66.75,  66.5 ,  66.25,
         66.  ,  65.75,  65.5 ,  65.25,  

In [17]:
#lats,lons = tem700.latlons()
#lats,lons 这是个矩阵

In [18]:
#lats,lons 这是个矩阵

In [26]:
datasets = []
datasets1 = []
datasets2 = []
datasets3 = []
datasets4 = []
datasets5 = []
datasets6 = []
datasets7 = []
datasets8 = []
datasets9 = []
datasets10 = []
datasets11 = []
datasets12 = []
datasets13 = []
datasets14 = []
datasets15 = []
datasets16 = []
datasets17 = []
datasets18 = []
datasets19 = []
datasets20 = []
datasets21 = []
datasets22 = []
datasets23 = []
datasets24 = []
datasets25 = []
datasets26 = []
datasets27 = []
datasets28 = []
for x,y in zip(lon,lat):
        #print(x)
        #print(y)
    x_indice = np.where(lon_list == find_nearest(lon_list,x))[0]
    y_indice = np.where(lat_list== find_nearest(lat_list,y))[0]
    #print(x_indice)
    #print(y_indice)
    #print(pbl.shape)
    #print(lts.shape)
    PBLH=np.around(pblhv[y_indice,x_indice][0], decimals=2)
    LTS=np.around(lts[y_indice,x_indice][0], decimals=2)
    #TEMS=np.around(temsv[y_indice,x_indice][0], decimals=2)
    PTEMS=np.around(ptemsv[y_indice,x_indice][0], decimals=2)-273.15
    PTEM700=np.around(ptem700v[y_indice,x_indice][0], decimals=2)-273.15
    TD2=np.around(TD2v[y_indice,x_indice][0], decimals=2)-273.15
    RH2=np.around(RH2v[y_indice,x_indice][0], decimals=2)
    SH2=np.around(Sh2v[y_indice,x_indice][0], decimals=2)
    PW=np.around(Pwv[y_indice,x_indice][0], decimals=2)
    PR=np.around(Prv[y_indice,x_indice][0], decimals=2)
    CAPE=np.around(Capev[y_indice,x_indice][0], decimals=2)
    SRH=np.around(Srhv[y_indice,x_indice][0], decimals=2)
    TOZONE=np.around(Tozonev[y_indice,x_indice][0], decimals=2)
    LSM=np.around(LSMv[y_indice,x_indice][0], decimals=2)
    B4LI=np.around(B4liv[y_indice,x_indice][0], decimals=2)
    SLI=np.around(Sliv[y_indice,x_indice][0], decimals=2)
    ST0=np.around(ST0v[y_indice,x_indice][0], decimals=2)
    GH1000=np.around(Gh1000v[y_indice,x_indice][0], decimals=2)
    GH850=np.around(Gh850v[y_indice,x_indice][0], decimals=2)
    GH700=np.around(Gh700v[y_indice,x_indice][0], decimals=2)
    GH500=np.around(Gh500v[y_indice,x_indice][0], decimals=2)
    TSURF=np.around(Tsurfv[y_indice,x_indice][0], decimals=2)-273.15
    T1000=np.around(T1000v[y_indice,x_indice][0], decimals=2)-273.15
    T850=np.around(T850v[y_indice,x_indice][0], decimals=2)-273.15
    T700=np.around(T700v[y_indice,x_indice][0], decimals=2)-273.15
    T500=np.around(T500v[y_indice,x_indice][0], decimals=2)-273.15
    CIN0=np.around(CIN0v[y_indice,x_indice][0], decimals=2)
    CIN180=np.around(CIN180v[y_indice,x_indice][0], decimals=2)
    CIN255=np.around(CIN255v[y_indice,x_indice][0], decimals=2)
    datasets.append(PBLH)
    datasets1.append(LTS)
    #datasets2.append(TEMS)
    datasets3.append(PTEMS)
    datasets4.append(PTEM700)
    datasets5.append(TD2)
    datasets6.append(RH2)
    datasets7.append(SH2)
    datasets8.append(PW)
    datasets9.append(PR)
    datasets10.append(CAPE)
    datasets11.append(SRH)
    datasets12.append(TOZONE)
    datasets13.append(LSM)
    datasets14.append(B4LI)
    datasets15.append(SLI)
    datasets16.append(ST0)
    datasets17.append(GH1000)
    datasets18.append(GH850)
    datasets19.append(GH700)
    datasets20.append(GH500)
    datasets21.append(TSURF)
    datasets22.append(T1000)
    datasets23.append(T850)
    datasets24.append(T700)
    datasets25.append(T500)
    datasets26.append(CIN0)
    datasets27.append(CIN180)
    datasets28.append(CIN255)
print(len(datasets))
print(len(datasets1))
#print(len(datasets2))
print(len(datasets3))
print(len(datasets4))
#df["PBLH"],df['LCT']=datasets,datasets1
#df.to_csv("test.csv",index=True,sep=',')
    


3057
3057
3057
3057


In [27]:
df["PBLH"],df['LTS'],df['PTEMS'],df['PTEM700'],df["TD2"],df["RH2"],df['SH2'],df['PW'],df['PR'],\
df["CAPE"],df['SRH'],df['TOZONE'],df['LSM'],df['B4LI'],df["SLI"],df["ST0"],df['GH1000'],df['GH850'],df['GH700'],\
df["GH500"],df['TSURF'],df['T1000'],df['T850'],df['T700'],df["T500"],df["CIN0"],df['CIN180'],df['CIN255'] \
= datasets,datasets1,datasets3,datasets4,datasets5,datasets6,datasets7,datasets8,datasets9,\
  datasets10,datasets11,datasets12,datasets13,datasets14,datasets15,datasets16,datasets17,datasets18,datasets19,\
  datasets20,datasets21,datasets22,datasets23,datasets24,datasets25,datasets26,datasets27,datasets28
df.to_csv("test.csv",index=True,sep=',')

In [ ]:
#datasets1

pbl[y_indice,x_indice] this will get:
3056,22708,4384,3264,23.5881,134.1529,4288,3072,0.0,0.0,0.0,0.0,31.9,22.02,11.01,1011.0,27.5,75,-0.48,0.03,28.0,2,0,-75.3,16114,111,284,,,942,21.5,603.9,970.0,970.0,24.0,24.0,367.0,367.0,9.6,9.6,346.0,346.0,0.31,0.31,,,,,,,883.0,883.0,20.0,20.0,11.9,11.9,1189.0,1189.0,,,,,,,,,,,24.0,24.0,,,,,,,80.0,80.0,1.0,0.0087,-0.7395,0.0238,0.0232,10.61,30.0,27.85,27.43,285.0,276.0,80.0,80.0,80.0,80.0,0.0,0.0,,,,,,,,,,,,,,[374.04],[0.62]
should call pbl[y_indice,x_indice][0]

In [ ]:
#df.to_csv("test1.csv",index=True,sep=',')

In [28]:
df.head(10)

winNO  big_c  big_r      lat       lon  colum   row  Have   Hsd   Hmax  \
0  22802   4096   3264  37.3944  124.6297   4000  3264   0.0   0.0    0.0   
1  22805   4096   3264  37.7066  124.5471   4000  3168   0.0   6.0  143.0   
2  22806   4096   3264  37.6469  124.0689   3904  3168   0.0   0.0    0.0   
3  22807   4096   3264  38.0790  124.9651   4096  3072  34.0  60.0  404.0   
4  22808   4096   3264  38.0190  124.4641   4000  3072   1.0   8.0  134.0   
5  22809   4096   3264  37.9589  123.9830   3904  3072   0.0   0.0    0.0   
6  22901   3808   3264  37.2766  123.6943   3808  3264   0.0   0.0    0.0   
7  22902   3808   3264  37.2183  123.2483   3712  3264   0.0   0.0    0.0   
8  22903   3808   3264  37.1595  122.8148   3616  3264   0.0   0.0    0.0   
9  22904   3808   3264  37.5887  123.6069   3808  3168   0.0   0.0    0.0   

   ...        GH500      TSURF      T1000       T850      T700      T500  \
0  ...  5798.129883  25.050012  24.550012  17.450006  6.249994 -6.850012   
1  ...  5796.370117  23.350000  24.649988  16.950006  6.249994 -7.150000   
2  ...  5798.209961  26.249994  25.249994  16.749994  6.350000 -6.850012   
3  ...  5793.009766  23.249994  27.149988  16.850000  6.149988 -7.549994   
4  ...  5794.370117  23.450006  24.950006  16.850000  6.249994 -7.449988   
5  ...  5796.290039  25.950006  25.149988  16.649988  6.450006 -7.150000   
6  ...  5803.209961  28.149988  26.050012  17.149988  6.850000 -5.949988   
7  ...  5805.890137  26.950006  25.850000  17.050012  6.850000 -5.650000   
8  ...  5808.490234  24.850000  24.950006  17.149988  6.749994 -5.850012   
9  ...  5802.689941  27.450006  26.050012  16.850000  6.550012 -6.250006   

   CIN0  CIN180  CIN225  CIN255  
0 -57.0   -55.0   -57.0   -57.0  
1 -56.0   -51.0   -56.0   -56.0  
2 -26.0   -30.0   -26.0   -26.0  
3 -11.0   -12.0   -11.0   -11.0  
4 -42.0   -47.0   -42.0   -42.0  
5 -24.0   -27.0   -24.0   -24.0  
6 -20.0   -20.0   -20.0   -20.0  
7 -28.0   -23.0   -28.0   -28.0  
8 -40.0   -44.0   -40.0   -40.0  
9 -24.0   -25.0   -24.0   -24.0  

[10 rows x 136 columns]