In [23]:
import numpy as np
from dateutil.relativedelta import *
import datetime as dt
import os
import pandas as pd

In [3]:
def search(s, path=os.path.abspath('.')):  #os.path.abspath(path)：绝对路径
    filenames=[]
    for z in os.listdir(path):
        if os.path.isdir(path + os.path.sep + z):  # os.path.sep:路径分隔符 linux下就用这个了’/’
            #print('Currnet:', path)
            path2 = os.path.join(path, z) #；os.path.join(): 常用来链接路径
            #print('future:', path2)
            search(s, path2)
        elif os.path.isfile(path + os.path.sep + z): #检验给出的路径是否是一个文件：os.path.isfile()来自 <http://blog.csdn.net/devil_2009/article/details/7941241>
            if s in z:
                #print(os.path.join(path, z))
                filenames.append(os.path.join(path, z))
                #with open(path + os.path.sep + z, 'r') as fr:
                #    with open('save.txt', 'a') as fw:
                #        fw.write(path + '\t' + fr.read())
    return filenames

In [4]:
filenames=search('.grd', './')

In [5]:
filenames

['./SEVP_CLI_CHN_MERGE_CMP_PRE_HOUR_GRID_0.10-2013081518.grd',
 './SEVP_CLI_CHN_MERGE_CMP_PRE_HOUR_GRID_0.10-2013081618.grd']

In [6]:
l=np.zeros(shape=(440,700,0))

In [7]:
l

array([], shape=(440, 700, 0), dtype=float64)

In [9]:
data=np.fromfile(filenames[0],dtype=np.float32)

In [10]:
data=data.reshape(2,440,700)

In [11]:
pre=np.maximum(data[0,:,:],0)

In [13]:
count=np.where(pre>0.1,1,0)

In [14]:
count

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
np.savetxt('test.csv',count,delimiter=',')

In [19]:
count.size

308000

In [27]:
unique_elements, counts_elements = np.unique(count, return_counts=True)

In [28]:
unique_elements

array([0, 1])

In [29]:
counts_elements

array([274329,  33671], dtype=int64)

In [32]:
data1=np.fromfile(filenames[1],dtype=np.float32)

In [33]:
data1=data1.reshape(2,440,700)

In [34]:
pre1=np.maximum(data1[0,:,:],0)

In [35]:
count1=np.where(pre1>0.1,1,0)

In [36]:
count1.size

308000

In [37]:
unique_elements, counts_elements = np.unique(count, return_counts=True)

In [38]:
unique_elements

array([0, 1])

In [39]:
counts_elements

array([274329,  33671], dtype=int64)

In [40]:
b=274329+33671

In [41]:
b

308000

In [73]:
l=np.zeros(shape=(440,700,0))

In [74]:
l = np.dstack((l,pre))

In [75]:
l.shape

(440, 700, 1)

In [ ]:
count=np.where(>0.1,1,0)

In [76]:
l = np.dstack((l,pre1))

In [77]:
l.shape

(440, 700, 2)

In [78]:
count=np.where(l>0.1,1,0)

In [80]:
unique_elements, counts_elements = np.unique(count, return_counts=True)

In [81]:
unique_elements

array([0, 1])

In [82]:
counts_elements 

array([538700,  77300], dtype=int64)

In [83]:
b=538700+ 77300

In [84]:
b

616000

In [85]:
count.shape

(440, 700, 2)

In [86]:
out_count=np.sum(count,axis=2)

In [87]:
out_count.shape

(440, 700)

In [92]:
unique_elements, counts_elements = np.unique(out_count, return_counts=True)

In [93]:
unique_elements

array([0, 1, 2])

In [94]:
counts_elements

array([244959,  48782,  14259], dtype=int64)

In [97]:
c=244959+48782+14259

In [98]:
c

308000

In [99]:
out_count

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])