[用Python实现简单和多重线性回归--预测波士顿房价](https://www.jianshu.com/p/edaaa78fb6a1)

[译自](https://towardsdatascience.com/simple-and-multiple-linear-regression-in-python-c928425168f9)

[使用sklearn进行多元线性回归](https://stackoverflow.com/questions/46899217/multi-linear-regression-with-sklearn)

# SKLearn中的线性回归

In [1]:
from sklearn import linear_model

In [3]:
import pandas as pd

from sklearn import datasets ## 从scikit-learn导入数据集
data = datasets.load_boston() ## 从数据集库中加载波士顿数据集

In [5]:
df=pd.read_csv("yrd/yrd_ccn_new-all.csv")

In [6]:
df.head()

ID_1   ID_2    NAME_2  lat_bin  lon_bin             BJC  B4LI    CAPE  \
0   602  10098  Hangzhou     30.0    120.0  2014/7/21 5:35 -4.40  2565.0   
1   602  10098  Hangzhou     30.0    120.0  2015/8/12 4:31  1.40    10.0   
2   602  10098  Hangzhou     30.0    120.0  2013/8/25 5:12 -6.10  2428.0   
3   602  10098  Hangzhou     30.0    120.0   2017/7/8 5:19 -5.15  2083.0   
4   602  10098  Hangzhou     30.0    120.0  2017/7/25 5:00 -3.85  1252.5   

   CAPE_nc  CCN_1.0_cm3  ...  mean_wspd  max_wspd  max_wdir  ext_wspd    ssd  \
0   3044.0       1318.0  ...       15.5      41.0       3.5      60.0  104.0   
1    973.0       1072.0  ...       19.0      41.0       7.5      61.5   91.5   
2   2036.5       1553.5  ...       14.0      77.0      14.5     130.0   71.5   
3   1636.0       3103.0  ...       28.0      51.5      11.0      87.0   93.5   
4   1571.0       1672.5  ...       18.0      36.5       2.5      62.5  110.0   

   mean_prs  max_prs  min_prs  mean_rh  min_rh  
0   10034.0  10054.5  10011.0     72.0    47.0  
1   10055.0  10068.5  10035.0     75.0    51.0  
2   10030.0  10040.0  10008.5     75.0    45.0  
3   10041.0  10053.0  10026.0     67.0    50.5  
4   10011.5  10025.5      NaN     54.5    29.0  

[5 rows x 95 columns]

In [36]:
df1=df[["CCN_1.0_cm3","T2m_NCEP","SS_1.0_mg","PM25"]].dropna()

In [37]:
X = df1[["T2m_NCEP","SS_1.0_mg","PM25"]].values.reshape(-1,3)
y = df1["CCN_1.0_cm3"]

In [38]:
X

array([[35.75      ,  0.12      , 55.125     ],
       [29.45      ,  0.17      , 29.90909091],
       [32.91      ,  0.16      , 32.875     ],
       ...,
       [32.03      ,  0.12      , 29.        ],
       [33.85      ,  0.14      , 16.66666667],
       [30.19      ,  0.1       , 32.        ]])

In [39]:
lm = linear_model.LinearRegression()
model = lm.fit(X,y)

In [40]:
predictions = lm.predict(X)
print(predictions[0:5])

[1435.10739571 1216.33512192 1301.53162757 1302.0985245  1406.86292168]


In [41]:
lm.score(X,y)

0.3440653999518199

这是我们模型的R²得分。你可能记得，这是预测方差的百分比。如果你有兴趣，阅读这里了解更多内容。接下来，我们来看看预测因子的系数：

In [42]:
lm.coef_

array([ 1.93424177e+01, -1.66850834e+03,  5.34964880e-01])

和截距

In [43]:
lm.intercept_

914.3470255918077

In [ ]:
def mlr